In [1]:
import torch

In [2]:
def create_sample_tensor():
    """
    Return a torch Tensor of shape (3, 2) which is filled with zeros, except for
    element (0, 1) which is set to 10 and element (1, 0) which is set to 100.

    Inputs: None

    Returns:
    - Tensor of shape (3, 2) as described above.
    """
    x = torch.zeros(size=(3, 2))
    #############################################################################
    #                    TODO: Implement this function                          #
    #############################################################################
    x[0][1] = 10
    x[1][0] = 100
    #############################################################################
    #                            END OF YOUR CODE                               #
    #############################################################################
    return x

x = create_sample_tensor()
print(x)

tensor([[  0.,  10.],
        [100.,   0.],
        [  0.,   0.]])


In [3]:
def mutate_tensor(x, indices, values):
    """
    Mutate the PyTorch tensor x according to indices and values.
    Specifically, indices is a list [(i0, j0), (i1, j1), ... ] of integer indices,
    and values is a list [v0, v1, ...] of values. This function should mutate x
    by setting:

    x[i0, j0] = v0
    x[i1, j1] = v1

    and so on.

    If the same index pair appears multiple times in indices, you should set x to
    the last one.

    Inputs:
    - x: A Tensor of shape (H, W)
    - indicies: A list of N tuples [(i0, j0), (i1, j1), ..., ]
    - values: A list of N values [v0, v1, ...]

    Returns:
    - The input tensor x
    """
    #############################################################################
    #                    TODO: Implement this function                          #
    #############################################################################
    for idx, val in zip(indices, values):
        i, j = idx
        x[i, j] = val
    
    #############################################################################
    #                            END OF YOUR CODE                               #
    #############################################################################
    return x

x = mutate_tensor(x, [(0, 0), (1, 1)], [3, 2])
print(x)

tensor([[  3.,  10.],
        [100.,   2.],
        [  0.,   0.]])


In [4]:
def count_tensor_elements(x):
    """
    Count the number of scalar elements in a tensor x.

    For example, a tensor of shape (10,) has 10 elements.a tensor of shape (3, 4)
    has 12 elements; a tensor of shape (2, 3, 4) has 24 elements, etc.

    You may not use the functions torch.numel or x.numel. The input tensor should
    not be modified.

    Inputs:
    - x: A tensor of any shape

    Returns:
    - num_elements: An integer giving the number of scalar elements in x
    """
    num_elements = 1
    #############################################################################
    #                    TODO: Implement this function                          #
    #   You CANNOT use the built-in functions torch.numel(x) or x.numel().      #
    #############################################################################
    for num in x.size():
        num_elements *= num
    #############################################################################
    #                            END OF YOUR CODE                               #
    #############################################################################
    return num_elements

print(count_tensor_elements(x))

6


In [5]:
def create_tensor_of_pi(M, N):
    """
    Returns a Tensor of shape (M, N) filled entirely with the value 3.14

    Inputs:
    - M, N: Positive integers giving the shape of Tensor to create

    Returns:
    - x: A tensor of shape (M, N) filled with the value 3.14
    """
    x = torch.zeros(size=(M, N))
    #############################################################################
    #       TODO: Implement this function. It should take one line.             #
    #############################################################################
    # Replace "pass" statement with your code
    x[:, :] = torch.pi
    #############################################################################
    #                            END OF YOUR CODE                               #
    #############################################################################
    return x

create_tensor_of_pi(3, 2)

tensor([[3.1416, 3.1416],
        [3.1416, 3.1416],
        [3.1416, 3.1416]])

In [6]:
def multiples_of_ten(start, stop):
    """
    Returns a Tensor of dtype torch.float64 that contains all of the multiples of
    ten (in order) between start and stop, inclusive. If there are no multiples
    of ten in this range you should return an empty tensor of shape (0,).

    Inputs:
    - start, stop: Integers with start <= stop specifying the range to create.

    Returns:
    - x: Tensor of dtype float64 giving multiples of ten between start and stop.
    """
    assert start <= stop
    #############################################################################
    #                    TODO: Implement this function                          #
    #############################################################################
    
    # Compute the smallest multiple of ten that is >= start
    if start % 10 != 0:
        start = start + (10 - start % 10)

    # Compute the largest multiple of ten that is <= stop
    stop = stop - stop % 10

    # Check if there are no multiples of ten in the range
    if start > stop:
        x = torch.tensor([], dtype=torch.float64)
    else:
        # Generate the tensor of multiples of ten
        x = torch.arange(start, stop + 1, 10, dtype=torch.float64)
    
    #############################################################################
    #                            END OF YOUR CODE                               #
    #############################################################################
    return x

multiples_of_ten(1, 100)

tensor([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.],
       dtype=torch.float64)

In [7]:
def slice_indexing_practice(x):
    """
    Given a two-dimensional tensor x, extract and return several subtensors to
    practice with slice indexing. Each tensor should be created using a single
    slice indexing operation.

    The input tensor should not be modified.

    Input:
    - x: Tensor of shape (M, N) -- M rows, N columns with M >= 3 and N >= 5.

    Returns a tuple of:
    - last_row: Tensor of shape (N,) giving the last row of x. It should be a
        one-dimensional tensor.
    - third_col: Tensor of shape (M, 1) giving the third column of x.
        It should be a two-dimensional tensor.
    - first_two_rows_three_cols: Tensor of shape (2, 3) giving the data in the
        first two rows and first three columns of x.
    - even_rows_odd_cols: Two-dimensional tensor containing the elements in the
        even-valued rows and odd-valued columns of x.
    """
    assert x.shape[0] >= 3
    assert x.shape[1] >= 5
    last_row = None
    third_col = None
    first_two_rows_three_cols = None
    even_rows_odd_cols = None
    #############################################################################
    #                    TODO: Implement this function                          #
    #############################################################################
    M, N = x.shape
    
    last_row = x[M-1, :]
    third_col = x[:, 2]
    first_two_rows_three_cols = x[:2, :3]
    
    even_row_idx = [i for i in range(M) if i % 2 == 1]
    odd_col_idx = [j for j in range(N) if j % 2 == 0]
    even_rows = x[even_row_idx, :]
    even_rows_odd_cols = even_rows[:, odd_col_idx]
    
    #############################################################################
    #                            END OF YOUR CODE                               #
    #############################################################################
    out = (
        last_row,
        third_col,
        first_two_rows_three_cols,
        even_rows_odd_cols,
    )
    return out

x = torch.randn(6, 6)
print(x)

slice_indexing_practice(x)

tensor([[ 0.0470,  1.3683, -0.3991, -0.0672, -2.2077, -0.5628],
        [ 0.1765, -0.5895,  0.5461,  0.1979, -0.9206, -0.6501],
        [ 1.9693,  1.0864,  1.2956,  0.2773, -0.2656,  0.2592],
        [-0.2349, -0.1027, -1.0232,  1.0789, -0.0184, -1.5451],
        [-0.9607,  2.2951,  0.1725,  0.0844, -1.0673, -0.4812],
        [-0.5253,  1.3649, -0.1693, -0.4050,  0.0250,  0.1875]])


(tensor([-0.5253,  1.3649, -0.1693, -0.4050,  0.0250,  0.1875]),
 tensor([-0.3991,  0.5461,  1.2956, -1.0232,  0.1725, -0.1693]),
 tensor([[ 0.0470,  1.3683, -0.3991],
         [ 0.1765, -0.5895,  0.5461]]),
 tensor([[ 0.1765,  0.5461, -0.9206],
         [-0.2349, -1.0232, -0.0184],
         [-0.5253, -0.1693,  0.0250]]))

In [8]:
def slice_indexing_practice(x):
    """
    Given a two-dimensional tensor x, extract and return several subtensors to
    practice with slice indexing. Each tensor should be created using a single
    slice indexing operation.

    The input tensor should not be modified.

    Input:
    - x: Tensor of shape (M, N) -- M rows, N columns with M >= 3 and N >= 5.

    Returns a tuple of:
    - last_row: Tensor of shape (N,) giving the last row of x. It should be a
        one-dimensional tensor.
    - third_col: Tensor of shape (M, 1) giving the third column of x.
        It should be a two-dimensional tensor.
    - first_two_rows_three_cols: Tensor of shape (2, 3) giving the data in the
        first two rows and first three columns of x.
    - even_rows_odd_cols: Two-dimensional tensor containing the elements in the
        even-valued rows and odd-valued columns of x.
    """
    assert x.shape[0] >= 3
    assert x.shape[1] >= 5
    
    # Getting the last row
    last_row = x[-1, :]
    
    # Getting the third column
    third_col = x[:, 2:3]
    
    # Getting the first two rows and first three columns
    first_two_rows_three_cols = x[:2, :3]
    
    # Getting the even-valued rows and odd-valued columns. 
    # Note: Python's 0-based indexing means even row/column indices are actually odd-valued
    even_rows_odd_cols = x[1::2, ::2]
    
    out = (
        last_row,
        third_col,
        first_two_rows_three_cols,
        even_rows_odd_cols,
    )
    return out

slice_indexing_practice(x)

(tensor([-0.5253,  1.3649, -0.1693, -0.4050,  0.0250,  0.1875]),
 tensor([[-0.3991],
         [ 0.5461],
         [ 1.2956],
         [-1.0232],
         [ 0.1725],
         [-0.1693]]),
 tensor([[ 0.0470,  1.3683, -0.3991],
         [ 0.1765, -0.5895,  0.5461]]),
 tensor([[ 0.1765,  0.5461, -0.9206],
         [-0.2349, -1.0232, -0.0184],
         [-0.5253, -0.1693,  0.0250]]))

In [9]:
def slice_assignment_practice(x):
    """
    Given a two-dimensional tensor of shape (M, N) with M >= 4, N >= 6, mutate its
    first 4 rows and 6 columns so they are equal to:

    [0 1 2 2 2 2]
    [0 1 2 2 2 2]
    [3 4 3 4 5 5]
    [3 4 3 4 5 5]

    Your implementation must obey the following:
    - You should mutate the tensor x in-place and return it
    - You should only modify the first 4 rows and first 6 columns; all other
        elements should remain unchanged
    - You may only mutate the tensor using slice assignment operations, where you
        assign an integer to a slice of the tensor
    - You must use <= 6 slicing operations to achieve the desired result

    Inputs:
    - x: A tensor of shape (M, N) with M >= 4 and N >= 6

    Returns: x
    """
    #############################################################################
    #                    TODO: Implement this function                          #
    #############################################################################
    x[:2, :2] = torch.tensor([0, 1])
    x[:2, 2:6] = 2
    
    x[2:4, :4] = torch.tensor([3, 4, 3, 4])
    x[2:4, 4:6] = 5
    #############################################################################
    #                            END OF YOUR CODE                               #
    #############################################################################
    return x

x = torch.randn(4, 6)
print(slice_assignment_practice(x))

tensor([[0., 1., 2., 2., 2., 2.],
        [0., 1., 2., 2., 2., 2.],
        [3., 4., 3., 4., 5., 5.],
        [3., 4., 3., 4., 5., 5.]])


In [10]:
def shuffle_cols(x):
    """
    Re-order the columns of an input tensor as described below.

    Your implementation should construct the output tensor using a single integer
    array indexing operation. The input tensor should not be modified.

    Input:
    - x: A tensor of shape (M, N) with N >= 3

    Returns: A tensor y of shape (M, 4) where:
    - The first two columns of y are copies of the first column of x
    - The third column of y is the same as the third column of x
    - The fourth column of y is the same as the second column of x
    """
    y = None
    #############################################################################
    #                    TODO: Implement this function                          #
    #############################################################################
    y = torch.zeros(size=x.size())
    y[:, 0] = x[:, 0]
    y[:, 1] = x[:, 0]
    y[:, 2] = x[:, 2]
    y[:, 3] = x[:, 1]
    #############################################################################
    #                            END OF YOUR CODE                               #
    #############################################################################
    return y

x = torch.randn(4, 4)
print(x)
shuffle_cols(x)

tensor([[ 0.8930, -0.8847, -1.3107, -1.4281],
        [ 0.4373, -0.6120,  1.1659, -0.4659],
        [ 0.6700, -1.1257,  0.9108, -0.3485],
        [-1.0215,  1.6244,  0.9573, -0.0488]])


tensor([[ 0.8930,  0.8930, -1.3107, -0.8847],
        [ 0.4373,  0.4373,  1.1659, -0.6120],
        [ 0.6700,  0.6700,  0.9108, -1.1257],
        [-1.0215, -1.0215,  0.9573,  1.6244]])

In [11]:
def reverse_rows(x):
    """
    Reverse the rows of the input tensor.

    Your implementation should construct the output tensor using a single integer
    array indexing operation. The input tensor should not be modified.

    Input:
    - x: A tensor of shape (M, N)

    Returns: A tensor y of shape (M, N) which is the same as x but with the rows
            reversed; that is the first row of y is equal to the last row of x,
            the second row of y is equal to the second to last row of x, etc.
    """
    y = None
    #############################################################################
    #                    TODO: Implement this function                          #
    #############################################################################
    y = torch.zeros(size=x.size())
    rows = x.shape[0]
    for i in range(rows):
        y[i, :] = x[rows-i-1, :]
    #############################################################################
    #                            END OF YOUR CODE                               #
    #############################################################################
    return y

x = torch.randn(5, 3)
print(x)
print(reverse_rows(x))

tensor([[-1.6834, -0.5249,  0.2904],
        [ 0.4917,  1.4531,  0.4839],
        [-0.1546, -1.2765,  0.8918],
        [-0.8609, -0.8063,  1.4577],
        [-2.5110, -0.3585, -0.6673]])
tensor([[-2.5110, -0.3585, -0.6673],
        [-0.8609, -0.8063,  1.4577],
        [-0.1546, -1.2765,  0.8918],
        [ 0.4917,  1.4531,  0.4839],
        [-1.6834, -0.5249,  0.2904]])


In [12]:
def take_one_elem_per_col(x):
    """
    Construct a new tensor by picking out one element from each column of the
    input tensor as described below.

    The input tensor should not be modified.

    Input:
    - x: A tensor of shape (M, N) with M >= 4 and N >= 3.

    Returns: A tensor y of shape (3,) such that:
    - The first element of y is the second element of the first column of x
    - The second element of y is the first element of the second column of x
    - The third element of y is the fourth element of the third column of x
    """
    y = None
    #############################################################################
    #                    TODO: Implement this function                          #
    #############################################################################
    y = torch.zeros(3)
    y[0] = x[1, 0]
    y[1] = x[0, 1]
    y[2] = x[3, 2]
    #############################################################################
    #                            END OF YOUR CODE                               #
    #############################################################################
    return y

x = torch.randn(4, 4)
print(x)
print(take_one_elem_per_col(x))

tensor([[ 7.6369e-01,  8.0283e-01, -1.8417e+00,  1.1293e-03],
        [-3.1203e-01,  1.5228e-01, -2.5155e-01,  9.7667e-01],
        [ 5.7296e-01,  9.9878e-01,  6.9109e-01, -1.8780e+00],
        [ 4.9315e-01,  7.6733e-01,  2.4348e-01, -8.9005e-01]])
tensor([-0.3120,  0.8028,  0.2435])


In [13]:
def count_negative_entries(x):
    """
    Return the number of negative values in the input tensor x.

    Your implementation should perform only a single indexing operation on the
    input tensor. You should not use any explicit loops. The input tensor should
    not be modified.

    Input:
    - x: A tensor of any shape

    Returns:
    - num_neg: Integer giving the number of negative values in x
    """
    num_neg = 0
    #############################################################################
    #                    TODO: Implement this function                          #
    #############################################################################
    neg_x, neg_y = torch.where(x < 0)
    num_neg = neg_x.shape[0]
    #############################################################################
    #                            END OF YOUR CODE                               #
    #############################################################################
    return num_neg

x = torch.randn(4, 4)
print(x)
count_negative_entries(x)

tensor([[ 0.7570,  0.1197, -0.5099,  1.0844],
        [ 0.6646, -0.1421, -1.4828, -0.6374],
        [ 0.8589,  3.7240, -0.1104, -0.2912],
        [-0.9400, -0.0241, -1.8874, -1.7310]])


10

In [14]:
def make_one_hot(x):
    """
    Construct a tensor of one-hot-vectors from a list of Python integers.

    Input:
    - x: A list of N integers

    Returns:
    - y: A tensor of shape (N, C) and where C = 1 + max(x) is one more than the max
        value in x. The nth row of y is a one-hot-vector representation of x[n];
        In other words, if x[n] = c then y[n, c] = 1; all other elements of y are
        zeros. The dtype of y should be torch.float32.
    """
    y = None
    #############################################################################
    #                    TODO: Implement this function                          #
    #############################################################################
    N, C = len(x), 1 + max(x)
    y = torch.zeros(size=(N, C))
    for i in range(N):
        item = x[i]
        y[i, item] = 1
    #############################################################################
    #                            END OF YOUR CODE                               #
    #############################################################################
    return y

x = [i for i in range(5)]
print(make_one_hot(x))

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [16]:
def reshape_practice(x):
    """
    Given an input tensor of shape (24,), return a reshaped tensor y of shape
    (3, 8) such that

    y = [
        [x[0], x[1], x[2],  x[3],  x[12], x[13], x[14], x[15]],
        [x[4], x[5], x[6],  x[7],  x[16], x[17], x[18], x[19]],
        [x[8], x[9], x[10], x[11], x[20], x[21], x[22], x[23]],
    ]

    You must construct y by performing a sequence of reshaping operations on x
    (view, t, transpose, permute, contiguous, reshape, etc). The input tensor
    should not be modified.

    Input:
    - x: A tensor of shape (24,)

    Returns:
    - y: A reshaped version of x of shape (3, 8) as described above.
    """
    y = None
    #############################################################################
    #                    TODO: Implement this function                          #
    #############################################################################
    y = x.reshape(3, 8)
    #############################################################################
    #                            END OF YOUR CODE                               #
    #############################################################################
    return y

x = torch.randn(24)
print(x)
print(reshape_practice(x))

tensor([-1.9390,  0.6317, -1.1237,  2.1901, -0.5393,  0.5481, -1.9198, -1.7377,
        -0.1590,  0.0128, -1.0353, -0.0859,  0.4900, -0.8594, -1.1845,  0.7316,
        -0.5737, -1.0079, -1.2963, -0.6214, -0.0471, -1.2295, -0.0239,  0.1572])
tensor([[-1.9390,  0.6317, -1.1237,  2.1901, -0.5393,  0.5481, -1.9198, -1.7377],
        [-0.1590,  0.0128, -1.0353, -0.0859,  0.4900, -0.8594, -1.1845,  0.7316],
        [-0.5737, -1.0079, -1.2963, -0.6214, -0.0471, -1.2295, -0.0239,  0.1572]])


In [25]:
def zero_row_min(x):
    """
    Return a copy of x, where the minimum value along each row has been set to 0.

    For example, if x is:
    x = torch.tensor([
            [10, 20, 30],
            [ 2,  5,  1]
        ])

    Then y = zero_row_min(x) should be:
    torch.tensor([
        [0, 20, 30],
        [2,  5,  0]
    ])

    Your implementation should use reduction and indexing operations; you should
    not use any explicit loops. The input tensor should not be modified.

    Inputs:
    - x: Tensor of shape (M, N)

    Returns:
    - y: Tensor of shape (M, N) that is a copy of x, except the minimum value
        along each row is replaced with 0.
    """
    
    y = x.clone()
    row_min_indices = torch.argmin(x, dim=1)
    row_indices = torch.arange(x.shape[0])
    y[row_indices, row_min_indices] = 0
    return y

x = torch.randint(low=1, high=100, size=(4, 4))
print(x)
print(zero_row_min(x))

tensor([[82, 33, 41, 54],
        [ 1, 60,  2, 74],
        [43, 65, 65, 23],
        [76,  1, 13, 13]])
tensor([[82,  0, 41, 54],
        [ 0, 60,  2, 74],
        [43, 65, 65,  0],
        [76,  0, 13, 13]])


In [26]:
def mm_on_gpu(x, w):
    """
    Perform matrix multiplication on GPU

    Specifically, you should (i) place each input on GPU first, and then
    (ii) perform the matrix multiplication operation. Finally, (iii) return the
    final result, which is on CPU for a fair in-place replacement with the mm_on_cpu.

    When you move the tensor to GPU, PLEASE use "your_tensor_intance.cuda()" operation.

    Input:
    - x: Tensor of shape (A, B), on CPU
    - w: Tensor of shape (B, C), on CPU

    Returns:
    - y: Tensor of shape (A, C) as described above. It should not be in GPU.
    """
    
    # Move tensors to GPU
    x_gpu = x.cuda()
    w_gpu = w.cuda()
    
    # Perform matrix multiplication on GPU
    y_gpu = x_gpu.mm(w_gpu)
    
    # Move result back to CPU
    y = y_gpu.cpu()
    
    return y

x = torch.randn(4, 3)
y = torch.randn(3, 2)

print(mm_on_gpu(x, y))

tensor([[-0.2494, -2.0566],
        [ 0.5065,  0.1605],
        [ 0.2388,  1.0351],
        [ 0.8338,  2.7330]])


In [31]:
def batched_matrix_multiply(x, y, use_loop=True):
    """
    Perform batched matrix multiplication between the tensor x of shape (B, N, M)
    and the tensor y of shape (B, M, P).

    If use_loop=True, then you should use an explicit loop over the batch
    dimension B. If loop=False, then you should instead compute the batched
    matrix multiply without an explicit loop using a single PyTorch operator.

    Inputs:
    - x: Tensor of shape (B, N, M)
    - y: Tensor of shape (B, M, P)
    - use_loop: Whether to use an explicit Python loop.

    Hint: torch.stack, bmm

    Returns:
    - z: Tensor of shape (B, N, P) where z[i] of shape (N, P) is the result of
        matrix multiplication between x[i] of shape (N, M) and y[i] of shape
        (M, P). It should have the same dtype as x.
    """
    
    if use_loop:
        results = []
        for xi, yi in zip(x, y):
            results.append(mm_on_cpu(xi, yi))
        z = torch.stack(results)
    else:
        z = torch.bmm(x, y)
    
    return z

def mm_on_cpu(x, w):
    """
    (helper function) Perform matrix multiplication on CPU.
    PLEASE DO NOT EDIT THIS FUNCTION CALL.

    Input:
    - x: Tensor of shape (A, B), on CPU
    - w: Tensor of shape (B, C), on CPU

    Returns:
    - y: Tensor of shape (A, C) as described above. It should not be in GPU.
    """
    y = x.mm(w)
    return y

B = 5
x = torch.randn(B, 4, 3)
y = torch.randn(B, 3, 2)

In [32]:
%%time
print(batched_matrix_multiply(x, y))

tensor([[[-1.2391,  0.9619],
         [ 1.0563, -0.2973],
         [-2.6471,  1.6169],
         [-1.6114,  2.5486]],

        [[-0.0909, -2.3243],
         [-0.2765,  1.2771],
         [ 0.6526,  0.0677],
         [ 0.1805,  2.5951]],

        [[ 0.6110, -0.9223],
         [ 0.4607, -0.4701],
         [-0.3135, -0.0304],
         [ 0.5366, -1.1630]],

        [[-1.5581, -0.3103],
         [-1.2317, -0.3475],
         [ 0.2468,  0.4873],
         [-0.7334, -0.5932]],

        [[-0.0343,  0.3308],
         [-0.3402,  2.4208],
         [-0.2126, -0.3742],
         [ 0.1167,  1.1282]]])
CPU times: user 2.1 ms, sys: 2.42 ms, total: 4.52 ms
Wall time: 3.3 ms


In [33]:
%%time
print(batched_matrix_multiply(x, y, use_loop=False))

tensor([[[-1.2391,  0.9619],
         [ 1.0563, -0.2973],
         [-2.6471,  1.6169],
         [-1.6114,  2.5486]],

        [[-0.0909, -2.3243],
         [-0.2765,  1.2771],
         [ 0.6526,  0.0677],
         [ 0.1805,  2.5951]],

        [[ 0.6110, -0.9223],
         [ 0.4607, -0.4701],
         [-0.3135, -0.0304],
         [ 0.5366, -1.1630]],

        [[-1.5581, -0.3103],
         [-1.2317, -0.3475],
         [ 0.2468,  0.4873],
         [-0.7334, -0.5932]],

        [[-0.0343,  0.3308],
         [-0.3402,  2.4208],
         [-0.2126, -0.3742],
         [ 0.1167,  1.1282]]])
CPU times: user 106 ms, sys: 0 ns, total: 106 ms
Wall time: 6.46 ms


In [1]:
from nltk.tokenize import word_tokenize

In [2]:
text = "안녕하세요! 오늘은 좋은 날씨네요."
tokens = word_tokenize(text)
print(tokens)

['안녕하세요', '!', '오늘은', '좋은', '날씨네요', '.']
